/**
 * Provider Preference Service Tests
 * Tests for the provider preference service
 */

const ProviderPreferenceService = require('../../src/preferences/provider-preference.service.js');

describe('Provider Preference Service', () => {
  let providerPreferenceService;

  beforeEach(() => {
    providerPreferenceService = new ProviderPreferenceService();
  });

  describe('getProviderPreferences', () => {
    test('should retrieve provider preferences correctly', () => {
      const providerId = 'PROV-12345';
      const preferences = providerPreferenceService.getProviderPreferences(providerId);

      expect(preferences).toBeDefined();
      expect(typeof preferences).toBe('object');
    });

    test('should throw an error for missing provider ID', () => {
      expect(() => {
        providerPreferenceService.getProviderPreferences(null);
      }).toThrow('Provider ID is required');
    });
  });

  describe('setProviderPreference', () => {
    test('should set provider preference correctly', () => {
      const providerId = 'PROV-12345';
      const category = 'decisionSupport';
      const preferenceKey = 'confidenceThreshold';
      const value = 0.9;

      const preferences = providerPreferenceService.setProviderPreference(
        providerId,
        category,
        preferenceKey,
        value
      );

      expect(preferences).toBeDefined();
      expect(preferences.preferences[category][preferenceKey]).toBe(value);
    });

    test('should throw an error for missing provider ID', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          null,
          'decisionSupport',
          'confidenceThreshold',
          0.9
        );
      }).toThrow('Provider ID is required');
    });

    test('should throw an error for missing category', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          null,
          'confidenceThreshold',
          0.9
        );
      }).toThrow('Category is required');
    });

    test('should throw an error for missing preference key', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          'decisionSupport',
          null,
          0.9
        );
      }).toThrow('Preference key is required');
    });

    test('should validate numeric preference values', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          'decisionSupport',
          'confidenceThreshold',
          'invalid'
        );
      }).toThrow('Preference confidenceThreshold must be a number');
    });

    test('should validate numeric preference range', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          'decisionSupport',
          'confidenceThreshold',
          1.5
        );
      }).toThrow('Preference confidenceThreshold must be at most 0.99');
    });

    test('should validate boolean preference values', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          'decisionSupport',
          'autoGenerateDecisions',
          'invalid'
        );
      }).toThrow('Preference autoGenerateDecisions must be a boolean');
    });

    test('should validate string preference values', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          'interface',
          'theme',
          'invalid-theme'
        );
      }).toThrow('Preference theme must be one of: light, dark, auto');
    });

    test('should validate array preference values', () => {
      expect(() => {
        providerPreferenceService.setProviderPreference(
          'PROV-12345',
          'alerts',
          'alertNotificationMethods',
          ['invalid-method']
        );
      }).toThrow('Preference alertNotificationMethods array items must be one of: dashboard, email, sms, push');
    });
  });

  describe('updateProviderPreferences', () => {
    test('should update multiple provider preferences correctly', () => {
      const providerId = 'PROV-12345';
      const preferences = {
        decisionSupport: {
          confidenceThreshold: 0.85,
          autoGenerateDecisions: true
        },
        interface: {
          theme: 'dark',
          language: 'es'
        }
      };

      const updatedPreferences = providerPreferenceService.updateProviderPreferences(
        providerId,
        preferences
      );

      expect(updatedPreferences).toBeDefined();
      expect(updatedPreferences.preferences.decisionSupport.confidenceThreshold).toBe(0.85);
      expect(updatedPreferences.preferences.decisionSupport.autoGenerateDecisions).toBe(true);
      expect(updatedPreferences.preferences.interface.theme).toBe('dark');
      expect(updatedPreferences.preferences.interface.language).toBe('es');
    });

    test('should throw an error for missing provider ID', () => {
      expect(() => {
        providerPreferenceService.updateProviderPreferences(null, {});
      }).toThrow('Provider ID is required');
    });

    test('should throw an error for missing preferences object', () => {
      expect(() => {
        providerPreferenceService.updateProviderPreferences('PROV-12345', null);
      }).toThrow('Preferences object is required');
    });
  });

  describe('resetProviderPreferences', () => {
    test('should reset provider preferences to defaults correctly', () => {
      const providerId = 'PROV-12345';

      // Set a custom preference first
      providerPreferenceService.setProviderPreference(
        providerId,
        'decisionSupport',
        'confidenceThreshold',
        0.9
      );

      // Reset to defaults
      const preferences = providerPreferenceService.resetProviderPreferences(providerId);

      expect(preferences).toBeDefined();
      // Should be back to default value of 0.8
      expect(preferences.preferences.decisionSupport.confidenceThreshold).toBe(0.8);
    });

    test('should throw an error for missing provider ID', () => {
      expect(() => {
        providerPreferenceService.resetProviderPreferences(null);
      }).toThrow('Provider ID is required');
    });
  });

  describe('getAvailableCategories', () => {
    test('should return available preference categories', () => {
      const categories = providerPreferenceService.getAvailableCategories();

      expect(categories).toBeDefined();
      expect(Array.isArray(categories)).toBe(true);
      expect(categories).toContain('decisionSupport');
      expect(categories).toContain('alerts');
      expect(categories).toContain('visualization');
      expect(categories).toContain('workflow');
      expect(categories).toContain('interface');
      expect(categories).toContain('notifications');
      expect(categories).toContain('privacy');
    });
  });

  describe('getCategoryConfiguration', () => {
    test('should retrieve category configuration correctly', () => {
      const configuration = providerPreferenceService.getCategoryConfiguration('decisionSupport');

      expect(configuration).toBeDefined();
      expect(configuration.name).toBe('Decision Support');
      expect(configuration.preferences).toBeDefined();
    });

    test('should return null for non-existent category', () => {
      const configuration = providerPreferenceService.getCategoryConfiguration('non-existent');
      expect(configuration).toBeNull();
    });
  });

  describe('getPreferenceConfiguration', () => {
    test('should retrieve preference configuration correctly', () => {
      const configuration = providerPreferenceService.getPreferenceConfiguration(
        'decisionSupport',
        'confidenceThreshold'
      );

      expect(configuration).toBeDefined();
      expect(configuration.name).toBe('Confidence Threshold');
      expect(configuration.type).toBe('number');
      expect(configuration.defaultValue).toBe(0.8);
    });

    test('should return null for non-existent category', () => {
      const configuration = providerPreferenceService.getPreferenceConfiguration(
        'non-existent',
        'confidenceThreshold'
      );
      expect(configuration).toBeNull();
    });

    test('should return null for non-existent preference', () => {
      const configuration = providerPreferenceService.getPreferenceConfiguration(
        'decisionSupport',
        'non-existent'
      );
      expect(configuration).toBeNull();
    });
  });

  describe('exportProviderPreferences', () => {
    test('should export provider preferences correctly', () => {
      const providerId = 'PROV-12345';

      const exportedPreferences = providerPreferenceService.exportProviderPreferences(providerId);

      expect(exportedPreferences).toBeDefined();
      expect(exportedPreferences.providerId).toBe(providerId);
      expect(exportedPreferences.preferences).toBeDefined();
      expect(exportedPreferences.exportedAt).toBeDefined();
      expect(exportedPreferences.version).toBe('1.0.0');
    });

    test('should throw an error for missing provider ID', () => {
      expect(() => {
        providerPreferenceService.exportProviderPreferences(null);
      }).toThrow('Provider ID is required');
    });
  });

  describe('importProviderPreferences', () => {
    test('should import provider preferences correctly', () => {
      const providerId = 'PROV-12345';
      const importedData = {
        preferences: {
          decisionSupport: {
            confidenceThreshold: 0.9,
            autoGenerateDecisions: true
          }
        }
      };

      const importedPreferences = providerPreferenceService.importProviderPreferences(
        providerId,
        importedData
      );

      expect(importedPreferences).toBeDefined();
      expect(importedPreferences.providerId).toBe(providerId);
      expect(importedPreferences.importedAt).toBeDefined();
    });

    test('should throw an error for missing provider ID', () => {
      expect(() => {
        providerPreferenceService.importProviderPreferences(null, {});
      }).toThrow('Provider ID is required');
    });

    test('should throw an error for missing preferences object', () => {
      expect(() => {
        providerPreferenceService.importProviderPreferences('PROV-12345', null);
      }).toThrow('Imported preferences object is required');
    });

    test('should throw an error for invalid preferences structure', () => {
      expect(() => {
        providerPreferenceService.importProviderPreferences('PROV-12345', {
          invalid: 'structure'
        });
      }).toThrow('Invalid preferences structure in import data');
    });
  });
});