/**
 * Provider Preference Management Configuration
 * Configuration for provider preference management system
 */

module.exports = {
  // Preference management settings
  management: {
    name: 'Provider Preference Management',
    version: '1.0.0',
    description: 'System for managing clinical decision support provider preferences',
    enabled: true,
    maxPreferencesPerProvider: 1000,
    defaultPreferenceScope: 'provider'
  },

  // Preference categories
  categories: {
    decisionSupport: {
      name: 'Decision Support',
      description: 'Preferences for clinical decision support functionality',
      preferences: {
        confidenceThreshold: {
          name: 'Confidence Threshold',
          description: 'Minimum confidence level for displaying recommendations',
          type: 'number',
          defaultValue: 0.8,
          min: 0.5,
          max: 0.99,
          step: 0.05
        },

        autoGenerateDecisions: {
          name: 'Auto-generate Decisions',
          description: 'Automatically generate decision support for new patients',
          type: 'boolean',
          defaultValue: false
        },

        decisionTypes: {
          name: 'Decision Types',
          description: 'Types of decisions to generate',
          type: 'array',
          defaultValue: ['diagnosis-support', 'treatment-recommendation'],
          options: [
            'diagnosis-support',
            'treatment-recommendation',
            'risk-assessment',
            'drug-interaction',
            'clinical-alert'
          ]
        },

        evidenceDisplay: {
          name: 'Evidence Display',
          description: 'Display evidence supporting recommendations',
          type: 'boolean',
          defaultValue: true
        }
      }
    },

    alerts: {
      name: 'Alerts',
      description: 'Preferences for clinical alert notifications',
      preferences: {
        alertSeverity: {
          name: 'Alert Severity',
          description: 'Minimum severity level for alerts',
          type: 'string',
          defaultValue: 'medium',
          options: ['low', 'medium', 'high', 'critical']
        },

        alertNotificationMethods: {
          name: 'Alert Notification Methods',
          description: 'Methods for receiving alert notifications',
          type: 'array',
          defaultValue: ['dashboard', 'email'],
          options: ['dashboard', 'email', 'sms', 'push']
        },

        autoAcknowledgeAlerts: {
          name: 'Auto-acknowledge Alerts',
          description: 'Automatically acknowledge alerts after a period',
          type: 'boolean',
          defaultValue: false
        },

        alertTimeout: {
          name: 'Alert Timeout',
          description: 'Time before auto-acknowledging alerts (in minutes)',
          type: 'number',
          defaultValue: 60,
          min: 5,
          max: 1440
        }
      }
    },

    visualization: {
      name: 'Visualization',
      description: 'Preferences for data visualization',
      preferences: {
        defaultChartType: {
          name: 'Default Chart Type',
          description: 'Default chart type for visualizations',
          type: 'string',
          defaultValue: 'bar',
          options: ['bar', 'line', 'pie', 'radar', 'scatter', 'heatmap']
        },

        showTooltips: {
          name: 'Show Tooltips',
          description: 'Display tooltips on visualizations',
          type: 'boolean',
          defaultValue: true
        },

        animationEnabled: {
          name: 'Animation Enabled',
          description: 'Enable animations in visualizations',
          type: 'boolean',
          defaultValue: true
        },

        colorScheme: {
          name: 'Color Scheme',
          description: 'Color scheme for visualizations',
          type: 'string',
          defaultValue: 'default',
          options: ['default', 'high-contrast', 'colorblind-friendly']
        }
      }
    },

    workflow: {
      name: 'Workflow',
      description: 'Preferences for clinical workflows',
      preferences: {
        defaultWorkflow: {
          name: 'Default Workflow',
          description: 'Default workflow for decision support',
          type: 'string',
          defaultValue: 'diagnosisSupport',
          options: [
            'diagnosisSupport',
            'treatmentRecommendation',
            'riskAssessment',
            'drugInteraction',
            'clinicalAlert'
          ]
        },

        parallelExecution: {
          name: 'Parallel Execution',
          description: 'Execute workflow steps in parallel',
          type: 'boolean',
          defaultValue: true
        },

        maxConcurrentWorkflows: {
          name: 'Max Concurrent Workflows',
          description: 'Maximum number of concurrent workflows',
          type: 'number',
          defaultValue: 10,
          min: 1,
          max: 50
        }
      }
    },

    interface: {
      name: 'Interface',
      description: 'Preferences for user interface',
      preferences: {
        theme: {
          name: 'Theme',
          description: 'User interface theme',
          type: 'string',
          defaultValue: 'light',
          options: ['light', 'dark', 'auto']
        },

        language: {
          name: 'Language',
          description: 'Interface language',
          type: 'string',
          defaultValue: 'en',
          options: ['en', 'es', 'fr', 'de', 'zh']
        },

        fontSize: {
          name: 'Font Size',
          description: 'Interface font size',
          type: 'string',
          defaultValue: 'medium',
          options: ['small', 'medium', 'large']
        },

        autoRefresh: {
          name: 'Auto-refresh',
          description: 'Automatically refresh dashboard data',
          type: 'boolean',
          defaultValue: true
        },

        refreshInterval: {
          name: 'Refresh Interval',
          description: 'Dashboard refresh interval (in seconds)',
          type: 'number',
          defaultValue: 30,
          min: 10,
          max: 300
        }
      }
    },

    notifications: {
      name: 'Notifications',
      description: 'Preferences for system notifications',
      preferences: {
        emailNotifications: {
          name: 'Email Notifications',
          description: 'Receive email notifications',
          type: 'boolean',
          defaultValue: true
        },

        smsNotifications: {
          name: 'SMS Notifications',
          description: 'Receive SMS notifications',
          type: 'boolean',
          defaultValue: false
        },

        pushNotifications: {
          name: 'Push Notifications',
          description: 'Receive push notifications',
          type: 'boolean',
          defaultValue: true
        },

        notificationSound: {
          name: 'Notification Sound',
          description: 'Play sound for notifications',
          type: 'boolean',
          defaultValue: true
        }
      }
    },

    privacy: {
      name: 'Privacy',
      description: 'Preferences for privacy and data handling',
      preferences: {
        anonymousMode: {
          name: 'Anonymous Mode',
          description: 'Hide patient identifiers in interface',
          type: 'boolean',
          defaultValue: false
        },

        dataRetention: {
          name: 'Data Retention',
          description: 'Data retention period (in days)',
          type: 'number',
          defaultValue: 365,
          min: 30,
          max: 3650
        },

        auditLogging: {
          name: 'Audit Logging',
          description: 'Enable detailed audit logging',
          type: 'boolean',
          defaultValue: true
        }
      }
    }
  },

  // Preference scopes
  scopes: {
    provider: {
      name: 'Provider',
      description: 'Preferences specific to individual provider',
      inheritable: false
    },

    department: {
      name: 'Department',
      description: 'Preferences for entire department',
      inheritable: true
    },

    organization: {
      name: 'Organization',
      description: 'Preferences for entire organization',
      inheritable: true
    },

    system: {
      name: 'System',
      description: 'System-wide default preferences',
      inheritable: true
    }
  },

  // Preference validation
  validation: {
    enabled: true,
    strictValidation: true,
    logValidationErrors: true
  },

  // Security settings
  security: {
    encryption: {
      enabled: true,
      algorithm: 'AES-256-GCM'
    },
    auditLogging: {
      enabled: true,
      retentionDays: 365
    },
    accessControl: {
      enabled: true,
      roleBasedAccess: true
    }
  },

  // Compliance settings
  compliance: {
    hipaa: {
      enabled: true,
      dataEncryption: true,
      auditLogging: true
    },
    gdpr: {
      enabled: true,
      dataProtection: true,
      consentManagement: true
    }
  }
};